import type { Metadata } from "next";
import Image from "next/image";
import { CtaStrip } from "../_components/cta-strip";
import { PageHero } from "../_components/page-hero";

export const metadata: Metadata = { title: "Where to Stay", description: "Choose the right Anuradhapura base for heritage visits, boutique calm, or a Wilpattu safari." };
const stayTypes = [{ number: "01", title: "Heritage comfort", copy: "Full-service hotels close to the sacred city, ideal for a smooth first visit and early starts.", best: "First-time visitors & families" }, { number: "02", title: "Boutique calm", copy: "Small, design-led stays with thoughtful hosts, garden settings, and a quieter atmosphere.", best: "Couples & slow travellers" }, { number: "03", title: "Wild-edge retreat", copy: "Nature lodges toward Wilpattu for dawn safaris, forest evenings, and star-filled skies.", best: "Wildlife journeys & two-night stays" }];

export default function StayPage() {
  return <main><PageHero eyebrow="Rest close to the story" title="Sleep well." italic="Start early." copy="The right base can transform the journey. We help you choose for location, atmosphere, and the experience you want—not the loudest listing." image="/places/isurumuniya.jpg" imageAlt="Rock temple landscape near Anuradhapura" /><section className="section stay-options"><div className="shell"><div className="stay-intro"><h2>Three ways to stay<br /><em>in the cultural north.</em></h2><p>We do not take commission for recommendations. We simply match the rhythm of your itinerary with the stay that makes it easier.</p></div><div className="stay-grid">{stayTypes.map((stay) => <article key={stay.number}><span>{stay.number}</span><h3>{stay.title}</h3><p>{stay.copy}</p><small>Best for</small><strong>{stay.best}</strong></article>)}</div></div></section><section className="stay-feature"><div className="shell stay-feature-grid"><div className="stay-feature-image"><Image src="/places/wilpattu.jpg" alt="Forest road through Wilpattu National Park" fill sizes="(max-width: 800px) 100vw, 55vw" /></div><div><p className="eyebrow eyebrow-light"><span />A two-base journey</p><h2>Ancient city.<br /><em>Wild morning.</em></h2><p>Spend the first night close to Anuradhapura, then move toward Wilpattu for a quieter evening and dawn safari. We help make the transfer feel like part of the journey.</p><a className="button button-gold" href="/contact?journey=heritage-wild-north">Plan heritage & wildlife <span>↗</span></a></div></div></section><CtaStrip /></main>;
}
